### ISSUE TITLE
Add quit button to Settings screen

### ISSUE THREAD

**Issue by iredchuk** [mdmsua/bitbucket-inbox#19]

**Comment by mdmsua** [comment]
I would rather add context menu (a.k.a. right click) with the quit action. What do you think?

**Comment by iredchuk** [comment]
Hm, left-click is not really "the thing" on macOS, I'm just comparing to the other clients I use, like Docker and Dropbox, and "quit" is left-click away.

**Comment by mdmsua** [comment]
Exactly. The way status bar works in macOS is it can be either menu (Docker, Skype, etc), or custom view (like in this project). So we need to think where to place it.
